# -*- coding: utf-8 -*-
"""main_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uuYe2T5Bu_IhejE94E5kbZe7UZgGSXvw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, ConfusionMatrixDisplay, f1_score
import time

from google.colab import drive
drive.mount('/content/drive')

train_x = train.drop(columns=['even','label'])
train_y = train['label']
val_x = val.drop(columns=['even','label'])
val_y = val['label']

train_x = train_x.to_numpy().astype(np.float64)/255.0
train_y = train_y.to_numpy()
val_x = val_x.to_numpy().astype(np.float64)/255.0
val_y= val_y.to_numpy()

# k = 5
# time taken = approx 88s

class KNNClassifier:
    def __init__(self, k=5):
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def _euclidean_distance(self, a, b):
        return np.sqrt(np.sum((a - b)**2, axis=1))

    def predict_one(self, x):
        distances = self._euclidean_distance(self.X_train, x)
        k_idx = np.argsort(distances)[:self.k]
        k_labels = self.y_train[k_idx]
        return np.bincount(k_labels).argmax()

    def predict(self, X):
        return np.array([self.predict_one(x) for x in X])

knn = KNNClassifier(k=5)
knn.fit(train_x, train_y)
# Predict on validation
start_time = time.time()
val_pred = knn.predict(val_x)
end_time = time.time()
accuracy = np.mean(val_pred == val_y)
print("KNN Validation Accuracy:", accuracy)
print("f1_score:", f1_score(val_y, val_pred, average='macro'))
print('Time taken(s):', end_time-start_time)